version: '2'
services:
  app:
    image: decidim/decidim:0.7.2-dev
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
    ports:
      - 3000:3000
    links:
      - pg
      - redis
    command: bundle exec rails s
  worker:
    image: decidim/decidim:0.7.2-dev
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
    links:
      - pg
      - redis
    command: bundle exec sidekiq
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
  redis-data: {}
