version: '2'
services:
  app:
    image: decidim/decidim:0.9-dev
    volumes:
      - .:/code:delegated
      - bundle:/usr/local/bundle:delegated
      - node_modules:/code/node_modules:delegated
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
    links:
      - pg
      - redis
    command: bundle exec puma
  worker:
    image: decidim/decidim:0.7.4-dev
    volumes:
      - .:/code:delegated
      - bundle:/usr/local/bundle:delegated
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    links:
      - pg
      - redis
    command: bundle exec sidekiq
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
  redis-data: {}
